version: '3'

services:
  mongo:
    image: 'mongo'
    container_name: 'mongodb'
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: FcFwdHqYp9Y9PV58
    volumes:
      - mongodb:/data/db
      - mongoconfig:/data/configdb
    command: [--auth]
    restart: always

volumes:
  mongodb:
  mongoconfig:
